name: Create PDF
on: push

jobs:
  lint:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.6.0"
      - run: |
          sudo apt install fonts-noto
          npm install
          npm run build
      - name: Commit PDF files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume
          git commit -m ":memo: [Auto] Generate resume.pdf "
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }} # github token

# アーティファクトとして職務経歴書をGithub上に保存する場合はコメントアウトすれば良い
# 最終的にPDFもGITで管理することにしたので不要になった（zipだと見づらい）
#      - uses: actions/upload-artifact@v1
#        with:
#          name: create-pdf
#          path: resume/README.pdf
